-- local Split = require("nui.split")
--
-- local sidebar_split = Split({
--   relative = "editor",
--   position = "right",
--   size = 30,
-- })
--
-- vim.cmd("NeoTree focus")
--
-- sidebar_split:mount()
